### ISSUE TITLE
I got error while update

### ISSUE THREAD

**Issue by featuriz** [Tony133/Symfony5ApiRest#4]
I downloaded the zip file from this gitrepo master and unpacked to a folder. and while update i got these error.
```

sudhakar@sudhakark-Desktop:~/SudhakarK/WORK/Garaje/Symfony5ApiRest$ composer update -o
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Package operations: 0 installs, 0 updates, 0 removals
Generating optimized autoload files
Deprecation Notice: Class App\Tests\Controller\HelloControllerTest located in ./tests/HelloControllerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class App\Tests\Controller\BookControllerTest located in ./tests/BookControllerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
70 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In BooleanNode.php line 29:
!!                                                                                 
!!    Invalid type for path "fos_rest.routing_loader". Expected boolean, but got   
!!    array.                                                                       
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
sudhakar@sudhakark-Desktop:~/SudhakarK/WORK/Garaje/Symfony5ApiRest$ 


```

**Comment by Tony133** [comment]
Hello,

use this command ```composer install``` when you download it the first time

**Comment by featuriz** [comment]
Still get error:
```
sudhakar@sudhakark-Desktop:~/SudhakarK/WORK/Garaje/Symfony5ApiRest$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
70 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In BooleanNode.php line 29:
!!                                                                                 
!!    Invalid type for path "fos_rest.routing_loader". Expected boolean, but got   
!!    array.                                                                       
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-install-cmd
sudhakar@sudhakark-Desktop:~/SudhakarK/WORK/Garaje/Symfony5ApiRest$ 

```

and File output:
```
# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: ROLE_ADMIN
    allowed_methods_listener: true
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
    versioning: true
    view:
        view_response_listener: 'force'
    routing_loader:
        default_format: json
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.

```
